// swift-tools-version: 6.0
import PackageDescription

// ChromaHash for Swift is a thin facade over UniFFI-generated bindings to the Rust
// core (no native algorithm). The generated Swift (Sources/ChromaHashBindings) and
// the ChromaHashFFI.xcframework (the static lib + C header/modulemap) are build
// outputs regenerated by `just swift-cbuild` — run it before `swift build`/`test`.
let package = Package(
    name: "ChromaHash",
    // `Synchronization.Mutex` (used by BatchEncoder) requires these minimums on
    // Apple platforms. No effect on Linux, where `Mutex` is always available.
    platforms: [
        .macOS(.v15),
        .iOS(.v18),
        .tvOS(.v18),
        .watchOS(.v11),
        .visionOS(.v2),
    ],
    products: [
        .library(name: "ChromaHash", targets: ["ChromaHash"]),
        .executable(name: "ChromaHashCLI", targets: ["ChromaHashCLI"]),
        .executable(name: "ChromaHashBatchBench", targets: ["ChromaHashBatchBench"]),
    ],
    targets: [
        // The Rust core's UniFFI scaffolding: static lib + C header/modulemap.
        .binaryTarget(name: "chromahash_uniffiFFI", path: "ChromaHashFFI.xcframework"),
        // UniFFI-generated Swift bindings (import the public ChromaHash facade, not this).
        .target(
            name: "ChromaHashBindings",
            dependencies: [.target(name: "chromahash_uniffiFFI")]
        ),
        // Public API: a thin facade preserving the idiomatic Swift surface.
        .target(name: "ChromaHash", dependencies: ["ChromaHashBindings"]),
        .executableTarget(name: "ChromaHashCLI", dependencies: ["ChromaHash"]),
        .executableTarget(name: "ChromaHashBatchBench", dependencies: ["ChromaHash"]),
        .testTarget(name: "ChromaHashTests", dependencies: ["ChromaHash"]),
    ]
)
