//! C ABI for ChromaHash.
//!
//! A hand-written `extern "C"` surface over the zero-dependency [`chromahash`]
//! core. The public header is generated by cbindgen (see `build.rs` /
//! `cbindgen.toml`) into `include/chromahash.h`. This is the first-class C API
//! and the FFI foundation the C# (P/Invoke) and Go (cgo) bindings link against.
//!
//! ## Conventions
//! - Fallible functions return a [`ChromaHashStatus`]; results are written
//!   through out-parameters. [`ChromaHashStatus::Ok`] (`0`) means success.
//! - [`ChromaHash`] and [`ChromaHashBatchEncoder`] are opaque handles: create
//!   them with a constructor and release them with the matching `*_free`.
//! - A decoded [`ChromaHashImage`] is owned by the library — release it with
//!   [`chromahash_image_free`]. Input RGBA buffers are read-only; the caller
//!   retains ownership.
//! - Every entry point is wrapped in [`std::panic::catch_unwind`]: a panic in the
//!   core surfaces as [`ChromaHashStatus::Internal`] instead of unwinding across
//!   the FFI boundary (which is undefined behaviour).

// Safety contracts are documented in the generated C header, not in rustdoc.
#![allow(clippy::missing_safety_doc)]

use std::os::raw::c_char;
use std::panic::{self, AssertUnwindSafe};
use std::ptr;
use std::sync::Arc;

use chromahash::{
    BatchEncoder as CoreBatch, ChromaHash as CoreHash, Gamut as CoreGamut, ImageInput as CoreInput,
    MAX_TIER,
};

/// Source/target color space. Mirrors [`chromahash::Gamut`].
#[repr(i32)]
#[derive(Debug, Clone, Copy)]
pub enum ChromaHashGamut {
    Srgb = 0,
    DisplayP3 = 1,
    AdobeRgb = 2,
    Bt2020 = 3,
    ProPhotoRgb = 4,
}

impl From<ChromaHashGamut> for CoreGamut {
    fn from(g: ChromaHashGamut) -> Self {
        match g {
            ChromaHashGamut::Srgb => CoreGamut::Srgb,
            ChromaHashGamut::DisplayP3 => CoreGamut::DisplayP3,
            ChromaHashGamut::AdobeRgb => CoreGamut::AdobeRgb,
            ChromaHashGamut::Bt2020 => CoreGamut::Bt2020,
            ChromaHashGamut::ProPhotoRgb => CoreGamut::ProPhotoRgb,
        }
    }
}

/// Status code returned by every fallible entry point. `Ok` is `0`.
#[repr(i32)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ChromaHashStatus {
    /// Success.
    Ok = 0,
    /// A required pointer argument was NULL.
    NullPointer = 1,
    /// A buffer length was wrong (rgba != width*height*4, or an output capacity
    /// was smaller than the hash's byte length).
    InvalidLength = 2,
    /// A dimension was zero.
    InvalidDimensions = 3,
    /// The core panicked or an allocation failed — caught at the boundary.
    Internal = 4,
    /// The bytes are not a valid v1 ChromaHash (bad version, tier, reserved bit,
    /// or the length does not match the self-describing header).
    InvalidData = 5,
}

/// A ChromaHash placeholder. Opaque handle; create with [`chromahash_encode`]
/// or [`chromahash_from_bytes`], release with [`chromahash_free`]. The encoded
/// form is variable length (32 bytes at tier 0); query it with
/// [`chromahash_byte_len`].
pub struct ChromaHash {
    inner: CoreHash,
}

/// A stateful batch encoder backed by a persistent worker pool. Opaque handle;
/// create with [`chromahash_batch_encoder_new`], release with
/// [`chromahash_batch_encoder_free`].
pub struct ChromaHashBatchEncoder {
    inner: CoreBatch,
}

/// A decoded RGBA image (≤ 32×32 px). `rgba` is library-owned and row-major,
/// 4 bytes/pixel (R, G, B, A); release the whole struct with
/// [`chromahash_image_free`].
#[repr(C)]
pub struct ChromaHashImage {
    pub width: u32,
    pub height: u32,
    pub rgba: *mut u8,
    pub rgba_len: usize,
}

/// An 8-bit-per-channel RGBA color.
#[repr(C)]
pub struct ChromaHashColor {
    pub r: u8,
    pub g: u8,
    pub b: u8,
    pub a: u8,
}

/// One image to encode in a batch. The caller owns `rgba` (read-only).
#[repr(C)]
pub struct ChromaHashImageInput {
    pub width: u32,
    pub height: u32,
    pub rgba: *const u8,
    pub rgba_len: usize,
    pub gamut: ChromaHashGamut,
}

// ─── helpers ──────────────────────────────────────────────────────────────────

/// rgba length must equal `width * height * 4`, computed without overflow.
fn expected_rgba_len(width: u32, height: u32) -> Option<usize> {
    (width as usize)
        .checked_mul(height as usize)
        .and_then(|p| p.checked_mul(4))
}

/// Hand a `Vec<u8>` to the C side as a (ptr, len) the library can free. The Vec is
/// shrunk to an exact allocation via `into_boxed_slice` so [`chromahash_image_free`]
/// can rebuild and drop it precisely.
fn make_image(width: u32, height: u32, rgba: Vec<u8>) -> ChromaHashImage {
    let boxed = rgba.into_boxed_slice();
    let rgba_len = boxed.len();
    let rgba = Box::into_raw(boxed) as *mut u8;
    ChromaHashImage {
        width,
        height,
        rgba,
        rgba_len,
    }
}

fn boxed_handle(inner: CoreHash) -> *mut ChromaHash {
    Box::into_raw(Box::new(ChromaHash { inner }))
}

// ─── construct ────────────────────────────────────────────────────────────────

/// Encode an RGBA image (4 bytes/pixel) into a tier-0 (32-byte) ChromaHash. On
/// success `*out_hash` receives a new handle to free with [`chromahash_free`].
#[no_mangle]
pub unsafe extern "C" fn chromahash_encode(
    width: u32,
    height: u32,
    rgba: *const u8,
    rgba_len: usize,
    gamut: ChromaHashGamut,
    out_hash: *mut *mut ChromaHash,
) -> ChromaHashStatus {
    if rgba.is_null() || out_hash.is_null() {
        return ChromaHashStatus::NullPointer;
    }
    if width == 0 || height == 0 {
        return ChromaHashStatus::InvalidDimensions;
    }
    if expected_rgba_len(width, height) != Some(rgba_len) {
        return ChromaHashStatus::InvalidLength;
    }
    let slice = std::slice::from_raw_parts(rgba, rgba_len);
    let result = panic::catch_unwind(AssertUnwindSafe(|| {
        boxed_handle(CoreHash::encode(width, height, slice, gamut.into()))
    }));
    match result {
        Ok(handle) => {
            *out_hash = handle;
            ChromaHashStatus::Ok
        }
        Err(_) => ChromaHashStatus::Internal,
    }
}

/// Encode an RGBA image at an explicit quality tier (`0..=3`; 0 is the 32-byte
/// default, each higher tier ~4× larger). Rejects an out-of-range tier with
/// [`ChromaHashStatus::InvalidData`]. On success `*out_hash` receives a new
/// handle to free with [`chromahash_free`].
#[no_mangle]
pub unsafe extern "C" fn chromahash_encode_with_quality(
    width: u32,
    height: u32,
    rgba: *const u8,
    rgba_len: usize,
    gamut: ChromaHashGamut,
    quality: u8,
    out_hash: *mut *mut ChromaHash,
) -> ChromaHashStatus {
    if rgba.is_null() || out_hash.is_null() {
        return ChromaHashStatus::NullPointer;
    }
    if width == 0 || height == 0 {
        return ChromaHashStatus::InvalidDimensions;
    }
    if expected_rgba_len(width, height) != Some(rgba_len) {
        return ChromaHashStatus::InvalidLength;
    }
    if quality > MAX_TIER {
        return ChromaHashStatus::InvalidData;
    }
    let slice = std::slice::from_raw_parts(rgba, rgba_len);
    let result = panic::catch_unwind(AssertUnwindSafe(|| {
        boxed_handle(CoreHash::encode_with_quality(
            width,
            height,
            slice,
            gamut.into(),
            quality,
        ))
    }));
    match result {
        Ok(handle) => {
            *out_hash = handle;
            ChromaHashStatus::Ok
        }
        Err(_) => ChromaHashStatus::Internal,
    }
}

/// Reconstruct a handle from a raw v1 hash of `len` bytes. The header is
/// self-describing, so `len` may be any tier's byte length; malformed bytes are
/// rejected with [`ChromaHashStatus::InvalidData`]. On success `*out_hash`
/// receives a new handle to free with [`chromahash_free`].
#[no_mangle]
pub unsafe extern "C" fn chromahash_from_bytes(
    bytes: *const u8,
    len: usize,
    out_hash: *mut *mut ChromaHash,
) -> ChromaHashStatus {
    if bytes.is_null() || out_hash.is_null() {
        return ChromaHashStatus::NullPointer;
    }
    let slice = std::slice::from_raw_parts(bytes, len);
    let result = panic::catch_unwind(AssertUnwindSafe(|| CoreHash::from_bytes(slice)));
    match result {
        Ok(Ok(inner)) => {
            *out_hash = boxed_handle(inner);
            ChromaHashStatus::Ok
        }
        Ok(Err(_)) => ChromaHashStatus::InvalidData,
        Err(_) => ChromaHashStatus::Internal,
    }
}

/// Release a handle from [`chromahash_encode`] / [`chromahash_from_bytes`].
/// NULL-safe.
#[no_mangle]
pub unsafe extern "C" fn chromahash_free(hash: *mut ChromaHash) {
    if !hash.is_null() {
        drop(Box::from_raw(hash));
    }
}

// ─── inspect / serialize ──────────────────────────────────────────────────────

/// The length in bytes of this hash's encoded form (32 at tier 0, more at higher
/// tiers or when an alpha channel is present). Returns 0 for a NULL handle. Use
/// it to size the buffer for [`chromahash_as_bytes`].
#[no_mangle]
pub unsafe extern "C" fn chromahash_byte_len(hash: *const ChromaHash) -> usize {
    if hash.is_null() {
        return 0;
    }
    (*hash).inner.as_bytes().len()
}

/// Copy the raw hash bytes into `out_buf`. `out_cap` must be ≥ the hash's byte
/// length ([`chromahash_byte_len`]); otherwise [`ChromaHashStatus::InvalidLength`].
#[no_mangle]
pub unsafe extern "C" fn chromahash_as_bytes(
    hash: *const ChromaHash,
    out_buf: *mut u8,
    out_cap: usize,
) -> ChromaHashStatus {
    if hash.is_null() || out_buf.is_null() {
        return ChromaHashStatus::NullPointer;
    }
    let handle = &*hash;
    let bytes = handle.inner.as_bytes();
    if out_cap < bytes.len() {
        return ChromaHashStatus::InvalidLength;
    }
    let result = panic::catch_unwind(AssertUnwindSafe(|| {
        // Inside the closure (a safe context) the raw copy needs its own block.
        unsafe { ptr::copy_nonoverlapping(bytes.as_ptr(), out_buf, bytes.len()) };
    }));
    match result {
        Ok(()) => ChromaHashStatus::Ok,
        Err(_) => ChromaHashStatus::Internal,
    }
}

/// Extract the average color without a full decode.
#[no_mangle]
pub unsafe extern "C" fn chromahash_average_color(
    hash: *const ChromaHash,
    out_color: *mut ChromaHashColor,
) -> ChromaHashStatus {
    if hash.is_null() || out_color.is_null() {
        return ChromaHashStatus::NullPointer;
    }
    let handle = &*hash;
    let result = panic::catch_unwind(AssertUnwindSafe(|| handle.inner.average_color()));
    match result {
        Ok([r, g, b, a]) => {
            *out_color = ChromaHashColor { r, g, b, a };
            ChromaHashStatus::Ok
        }
        Err(_) => ChromaHashStatus::Internal,
    }
}

// ─── decode (library allocates the image) ─────────────────────────────────────

unsafe fn decode_into(
    hash: *const ChromaHash,
    out_image: *mut ChromaHashImage,
    capped: Option<(u32, u32)>,
    output: CoreGamut,
) -> ChromaHashStatus {
    if hash.is_null() || out_image.is_null() {
        return ChromaHashStatus::NullPointer;
    }
    let handle = &*hash;
    let result = panic::catch_unwind(AssertUnwindSafe(|| {
        let (w, h, rgba) = match capped {
            Some((max_w, max_h)) => handle.inner.decode_capped_to(max_w, max_h, output),
            None => handle.inner.decode_to(output),
        };
        make_image(w, h, rgba)
    }));
    match result {
        Ok(image) => {
            *out_image = image;
            ChromaHashStatus::Ok
        }
        Err(_) => ChromaHashStatus::Internal,
    }
}

/// Decode into an sRGB RGBA image (≤ 32×32 px). `*out_image` receives a library-owned
/// image to release with [`chromahash_image_free`].
#[no_mangle]
pub unsafe extern "C" fn chromahash_decode(
    hash: *const ChromaHash,
    out_image: *mut ChromaHashImage,
) -> ChromaHashStatus {
    decode_into(hash, out_image, None, CoreGamut::Srgb)
}

/// Decode into an RGBA image in the given output gamut (sRGB / Display P3 /
/// Adobe RGB; others fall back to sRGB). `*out_image` receives a library-owned
/// image to release with [`chromahash_image_free`].
#[no_mangle]
pub unsafe extern "C" fn chromahash_decode_to(
    hash: *const ChromaHash,
    output: ChromaHashGamut,
    out_image: *mut ChromaHashImage,
) -> ChromaHashStatus {
    decode_into(hash, out_image, None, output.into())
}

/// Decode into an sRGB RGBA image, capped at the given maximum dimensions. `*out_image`
/// receives a library-owned image to release with [`chromahash_image_free`].
#[no_mangle]
pub unsafe extern "C" fn chromahash_decode_capped(
    hash: *const ChromaHash,
    max_width: u32,
    max_height: u32,
    out_image: *mut ChromaHashImage,
) -> ChromaHashStatus {
    decode_into(
        hash,
        out_image,
        Some((max_width, max_height)),
        CoreGamut::Srgb,
    )
}

/// Capped decode (see [`chromahash_decode_capped`]) in the given output gamut.
#[no_mangle]
pub unsafe extern "C" fn chromahash_decode_capped_to(
    hash: *const ChromaHash,
    max_width: u32,
    max_height: u32,
    output: ChromaHashGamut,
    out_image: *mut ChromaHashImage,
) -> ChromaHashStatus {
    decode_into(
        hash,
        out_image,
        Some((max_width, max_height)),
        output.into(),
    )
}

/// Release the RGBA buffer owned by a [`ChromaHashImage`] and zero the struct.
/// NULL-safe; safe to call once per successful decode.
#[no_mangle]
pub unsafe extern "C" fn chromahash_image_free(image: *mut ChromaHashImage) {
    if image.is_null() {
        return;
    }
    let img = &mut *image;
    if !img.rgba.is_null() {
        let slice = ptr::slice_from_raw_parts_mut(img.rgba, img.rgba_len);
        drop(Box::from_raw(slice));
        img.rgba = ptr::null_mut();
        img.rgba_len = 0;
    }
}

// ─── batch ────────────────────────────────────────────────────────────────────

/// Create a batch encoder with a worker pool sized to the available parallelism.
/// Returns NULL only if the pool could not be created. Free with
/// [`chromahash_batch_encoder_free`].
///
/// Not thread-safe: do not call [`chromahash_batch_encode`] on the same encoder
/// from multiple threads at once. Use one encoder per thread, or synchronize
/// externally. (A single batch already parallelizes internally across the pool.)
#[no_mangle]
pub extern "C" fn chromahash_batch_encoder_new() -> *mut ChromaHashBatchEncoder {
    panic::catch_unwind(|| {
        Box::into_raw(Box::new(ChromaHashBatchEncoder {
            inner: CoreBatch::new(),
        }))
    })
    .unwrap_or(ptr::null_mut())
}

/// Create a batch encoder with an explicit worker count (clamped to ≥ 1).
#[no_mangle]
pub extern "C" fn chromahash_batch_encoder_with_threads(
    threads: usize,
) -> *mut ChromaHashBatchEncoder {
    panic::catch_unwind(|| {
        Box::into_raw(Box::new(ChromaHashBatchEncoder {
            inner: CoreBatch::with_threads(threads),
        }))
    })
    .unwrap_or(ptr::null_mut())
}

/// Release a batch encoder. NULL-safe.
#[no_mangle]
pub unsafe extern "C" fn chromahash_batch_encoder_free(enc: *mut ChromaHashBatchEncoder) {
    if !enc.is_null() {
        drop(Box::from_raw(enc));
    }
}

/// Encode `count` images in parallel. `out_hashes` must point to an array of
/// `count` handle slots; on success each is set to a new handle to free
/// individually with [`chromahash_free`]. On any error no handle is allocated.
/// Output is byte-identical to calling [`chromahash_encode`] on each image.
#[no_mangle]
pub unsafe extern "C" fn chromahash_batch_encode(
    enc: *mut ChromaHashBatchEncoder,
    items: *const ChromaHashImageInput,
    count: usize,
    out_hashes: *mut *mut ChromaHash,
) -> ChromaHashStatus {
    if enc.is_null() {
        return ChromaHashStatus::NullPointer;
    }
    if count == 0 {
        return ChromaHashStatus::Ok;
    }
    if items.is_null() || out_hashes.is_null() {
        return ChromaHashStatus::NullPointer;
    }

    // Validate every item up front (mirroring the core's fail-fast) and copy each
    // image into an owned Arc<[u8]> so the worker pool never borrows caller memory.
    let raw_items = std::slice::from_raw_parts(items, count);
    let mut inputs: Vec<CoreInput> = Vec::with_capacity(count);
    for it in raw_items {
        if it.width == 0 || it.height == 0 {
            return ChromaHashStatus::InvalidDimensions;
        }
        if expected_rgba_len(it.width, it.height) != Some(it.rgba_len) {
            return ChromaHashStatus::InvalidLength;
        }
        if it.rgba.is_null() {
            return ChromaHashStatus::NullPointer;
        }
        let slice = std::slice::from_raw_parts(it.rgba, it.rgba_len);
        inputs.push(CoreInput {
            w: it.width,
            h: it.height,
            rgba: Arc::from(slice),
            gamut: it.gamut.into(),
            // Batch mirrors chromahash_encode: tier 0. Higher tiers are a future
            // additive API (chromahash_batch_encode_quality).
            quality: 0,
        });
    }

    let encoder = &*enc;
    let result = panic::catch_unwind(AssertUnwindSafe(|| encoder.inner.encode_batch(&inputs)));
    match result {
        Ok(hashes) => {
            for (i, hash) in hashes.into_iter().enumerate() {
                *out_hashes.add(i) = boxed_handle(hash);
            }
            ChromaHashStatus::Ok
        }
        Err(_) => ChromaHashStatus::Internal,
    }
}

// ─── version ──────────────────────────────────────────────────────────────────

/// The library version as a static, NUL-terminated string. Do not free.
#[no_mangle]
pub extern "C" fn chromahash_version() -> *const c_char {
    concat!(env!("CARGO_PKG_VERSION"), "\0")
        .as_ptr()
        .cast::<c_char>()
}
