// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(chromahash_uniffiFFI)
import chromahash_uniffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_chromahash_uniffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_chromahash_uniffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureChromahashUniffiInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt8: FfiConverterPrimitive {
    typealias FfiType = UInt8
    typealias SwiftType = UInt8

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt8 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: UInt8, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt32: FfiConverterPrimitive {
    typealias FfiType = Int32
    typealias SwiftType = Int32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int32, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        // Use Swift's native UTF-8 decoder; `String(bytes:encoding:.utf8)` goes
        // through Foundation's NSString and silently strips a leading U+FEFF BOM.
        // Invalid UTF-8 substitutes U+FFFD instead of trapping (unreachable
        // given Rust's `String` invariant).
        return String(decoding: bytes, as: UTF8.self)
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        // See `lift` above for why we avoid Foundation's NSString-backed decoder here.
        return String(decoding: try readBytes(&buf, count: Int(len)), as: UTF8.self)
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




/**
 * A stateful batch encoder backed by a persistent worker pool. Output is
 * byte-identical to calling [`ChromaHash::encode`] on each image individually.
 *
 * The core encoder is `!Sync` (it holds an `mpsc::Sender`), so it is wrapped in a
 * `Mutex` here to satisfy UniFFI's `Send + Sync` requirement for objects:
 * concurrent `encode_batch` calls on the same encoder serialize, but each call
 * still saturates the worker pool internally.
 */
public protocol BatchEncoderProtocol: AnyObject, Sendable {
    
    /**
     * Encode every item, returning hashes in the same order as `items`. Each
     * hash is byte-identical to [`ChromaHash::encode_with_quality`] on that
     * item at its `quality` tier.
     *
     * Every item is validated before any work is dispatched, so an invalid item
     * throws on the calling thread (naming its index) rather than panicking a
     * worker across the FFI boundary.
     */
    func encodeBatch(items: [ImageInput]) throws  -> [ChromaHash]
    
}
/**
 * A stateful batch encoder backed by a persistent worker pool. Output is
 * byte-identical to calling [`ChromaHash::encode`] on each image individually.
 *
 * The core encoder is `!Sync` (it holds an `mpsc::Sender`), so it is wrapped in a
 * `Mutex` here to satisfy UniFFI's `Send + Sync` requirement for objects:
 * concurrent `encode_batch` calls on the same encoder serialize, but each call
 * still saturates the worker pool internally.
 */
open class BatchEncoder: BatchEncoderProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_chromahash_uniffi_fn_clone_batchencoder(self.handle, $0) }
    }
    /**
     * Create an encoder with a worker pool sized to the available parallelism.
     */
public convenience init() {
    let handle =
        try! rustCall() {
    uniffi_chromahash_uniffi_fn_constructor_batchencoder_new($0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_chromahash_uniffi_fn_free_batchencoder(handle, $0) }
    }

    
    /**
     * Create an encoder with an explicit worker count (clamped to ≥ 1).
     */
public static func withThreads(threads: UInt32) -> BatchEncoder  {
    return try!  FfiConverterTypeBatchEncoder_lift(try! rustCall() {
    uniffi_chromahash_uniffi_fn_constructor_batchencoder_with_threads(
        FfiConverterUInt32.lower(threads),$0
    )
})
}
    

    
    /**
     * Encode every item, returning hashes in the same order as `items`. Each
     * hash is byte-identical to [`ChromaHash::encode_with_quality`] on that
     * item at its `quality` tier.
     *
     * Every item is validated before any work is dispatched, so an invalid item
     * throws on the calling thread (naming its index) rather than panicking a
     * worker across the FFI boundary.
     */
open func encodeBatch(items: [ImageInput])throws  -> [ChromaHash]  {
    return try  FfiConverterSequenceTypeChromaHash.lift(try rustCallWithError(FfiConverterTypeChromaHashError_lift) {
    uniffi_chromahash_uniffi_fn_method_batchencoder_encode_batch(
            self.uniffiCloneHandle(),
        FfiConverterSequenceTypeImageInput.lower(items),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeBatchEncoder: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = BatchEncoder

    public static func lift(_ handle: UInt64) throws -> BatchEncoder {
        return BatchEncoder(unsafeFromHandle: handle)
    }

    public static func lower(_ value: BatchEncoder) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> BatchEncoder {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: BatchEncoder, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBatchEncoder_lift(_ handle: UInt64) throws -> BatchEncoder {
    return try FfiConverterTypeBatchEncoder.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBatchEncoder_lower(_ value: BatchEncoder) -> UInt64 {
    return FfiConverterTypeBatchEncoder.lower(value)
}






/**
 * A ChromaHash placeholder (variable length — 32 bytes at the default tier).
 * Mirrors [`chromahash::ChromaHash`].
 */
public protocol ChromaHashProtocol: AnyObject, Sendable {
    
    /**
     * The raw hash bytes (32 at the default tier, more at higher tiers).
     */
    func asBytes()  -> Data
    
    /**
     * Extract the average color without a full decode.
     */
    func averageColor()  -> RgbaColor
    
    /**
     * Decode into an sRGB RGBA image (≤ 32×32 px).
     */
    func decode()  -> DecodeResult
    
    /**
     * Decode into an sRGB RGBA image, capped at the given maximum dimensions.
     */
    func decodeCapped(maxW: UInt32, maxH: UInt32)  -> DecodeResult
    
    /**
     * Capped decode (see `decode_capped`) in the given output gamut.
     */
    func decodeCappedTo(maxW: UInt32, maxH: UInt32, output: Gamut)  -> DecodeResult
    
    /**
     * Decode into an RGBA image in the given output gamut (sRGB / Display P3 /
     * Adobe RGB; others fall back to sRGB).
     */
    func decodeTo(output: Gamut)  -> DecodeResult
    
}
/**
 * A ChromaHash placeholder (variable length — 32 bytes at the default tier).
 * Mirrors [`chromahash::ChromaHash`].
 */
open class ChromaHash: ChromaHashProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_chromahash_uniffi_fn_clone_chromahash(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_chromahash_uniffi_fn_free_chromahash(handle, $0) }
    }

    
    /**
     * Encode an image (RGBA, 4 bytes/pixel) into a default-tier (32-byte)
     * ChromaHash. Throws if a dimension is zero or `rgba.len() != w * h * 4`.
     */
public static func encode(w: UInt32, h: UInt32, rgba: Data, gamut: Gamut)throws  -> ChromaHash  {
    return try  FfiConverterTypeChromaHash_lift(try rustCallWithError(FfiConverterTypeChromaHashError_lift) {
    uniffi_chromahash_uniffi_fn_constructor_chromahash_encode(
        FfiConverterUInt32.lower(w),
        FfiConverterUInt32.lower(h),
        FfiConverterData.lower(rgba),
        FfiConverterTypeGamut_lower(gamut),$0
    )
})
}
    
    /**
     * Encode at an explicit quality tier (0..=4, ordered by quality). Tier 1 is
     * the 32-byte default and tier 0 the 21-byte compact tier; each higher code
     * carries more detail in a larger hash. Throws on invalid dimensions, an
     * rgba length that disagrees with them, or a reserved tier code.
     */
public static func encodeWithQuality(w: UInt32, h: UInt32, rgba: Data, gamut: Gamut, quality: UInt8)throws  -> ChromaHash  {
    return try  FfiConverterTypeChromaHash_lift(try rustCallWithError(FfiConverterTypeChromaHashError_lift) {
    uniffi_chromahash_uniffi_fn_constructor_chromahash_encode_with_quality(
        FfiConverterUInt32.lower(w),
        FfiConverterUInt32.lower(h),
        FfiConverterData.lower(rgba),
        FfiConverterTypeGamut_lower(gamut),
        FfiConverterUInt8.lower(quality),$0
    )
})
}
    
    /**
     * Reconstruct from raw hash bytes. Throws [`ChromaHashError::InvalidData`] if
     * `bytes` is not a valid v1 ChromaHash.
     */
public static func fromBytes(bytes: Data)throws  -> ChromaHash  {
    return try  FfiConverterTypeChromaHash_lift(try rustCallWithError(FfiConverterTypeChromaHashError_lift) {
    uniffi_chromahash_uniffi_fn_constructor_chromahash_from_bytes(
        FfiConverterData.lower(bytes),$0
    )
})
}
    

    
    /**
     * The raw hash bytes (32 at the default tier, more at higher tiers).
     */
open func asBytes() -> Data  {
    return try!  FfiConverterData.lift(try! rustCall() {
    uniffi_chromahash_uniffi_fn_method_chromahash_as_bytes(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Extract the average color without a full decode.
     */
open func averageColor() -> RgbaColor  {
    return try!  FfiConverterTypeRgbaColor_lift(try! rustCall() {
    uniffi_chromahash_uniffi_fn_method_chromahash_average_color(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Decode into an sRGB RGBA image (≤ 32×32 px).
     */
open func decode() -> DecodeResult  {
    return try!  FfiConverterTypeDecodeResult_lift(try! rustCall() {
    uniffi_chromahash_uniffi_fn_method_chromahash_decode(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Decode into an sRGB RGBA image, capped at the given maximum dimensions.
     */
open func decodeCapped(maxW: UInt32, maxH: UInt32) -> DecodeResult  {
    return try!  FfiConverterTypeDecodeResult_lift(try! rustCall() {
    uniffi_chromahash_uniffi_fn_method_chromahash_decode_capped(
            self.uniffiCloneHandle(),
        FfiConverterUInt32.lower(maxW),
        FfiConverterUInt32.lower(maxH),$0
    )
})
}
    
    /**
     * Capped decode (see `decode_capped`) in the given output gamut.
     */
open func decodeCappedTo(maxW: UInt32, maxH: UInt32, output: Gamut) -> DecodeResult  {
    return try!  FfiConverterTypeDecodeResult_lift(try! rustCall() {
    uniffi_chromahash_uniffi_fn_method_chromahash_decode_capped_to(
            self.uniffiCloneHandle(),
        FfiConverterUInt32.lower(maxW),
        FfiConverterUInt32.lower(maxH),
        FfiConverterTypeGamut_lower(output),$0
    )
})
}
    
    /**
     * Decode into an RGBA image in the given output gamut (sRGB / Display P3 /
     * Adobe RGB; others fall back to sRGB).
     */
open func decodeTo(output: Gamut) -> DecodeResult  {
    return try!  FfiConverterTypeDecodeResult_lift(try! rustCall() {
    uniffi_chromahash_uniffi_fn_method_chromahash_decode_to(
            self.uniffiCloneHandle(),
        FfiConverterTypeGamut_lower(output),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeChromaHash: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = ChromaHash

    public static func lift(_ handle: UInt64) throws -> ChromaHash {
        return ChromaHash(unsafeFromHandle: handle)
    }

    public static func lower(_ value: ChromaHash) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ChromaHash {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: ChromaHash, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeChromaHash_lift(_ handle: UInt64) throws -> ChromaHash {
    return try FfiConverterTypeChromaHash.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeChromaHash_lower(_ value: ChromaHash) -> UInt64 {
    return FfiConverterTypeChromaHash.lower(value)
}




/**
 * A decoded RGBA image (≤ 32×32 px). `rgba` is row-major, 4 bytes/pixel (R, G, B, A).
 */
public struct DecodeResult: Equatable, Hashable {
    public var width: Int32
    public var height: Int32
    public var rgba: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(width: Int32, height: Int32, rgba: Data) {
        self.width = width
        self.height = height
        self.rgba = rgba
    }

    

    
}

#if compiler(>=6)
extension DecodeResult: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDecodeResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DecodeResult {
        return
            try DecodeResult(
                width: FfiConverterInt32.read(from: &buf), 
                height: FfiConverterInt32.read(from: &buf), 
                rgba: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: DecodeResult, into buf: inout [UInt8]) {
        FfiConverterInt32.write(value.width, into: &buf)
        FfiConverterInt32.write(value.height, into: &buf)
        FfiConverterData.write(value.rgba, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDecodeResult_lift(_ buf: RustBuffer) throws -> DecodeResult {
    return try FfiConverterTypeDecodeResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDecodeResult_lower(_ value: DecodeResult) -> RustBuffer {
    return FfiConverterTypeDecodeResult.lower(value)
}


/**
 * One image to encode in a batch. `rgba` is RGBA, 4 bytes/pixel
 * (length == `w * h * 4`). Mirrors [`chromahash::ImageInput`].
 */
public struct ImageInput: Equatable, Hashable {
    public var w: UInt32
    public var h: UInt32
    public var rgba: Data
    public var gamut: Gamut
    /**
     * Quality tier (`0..=4`, ordered by quality). Defaults to the 32-byte
     * default tier, matching [`ChromaHash::encode`] — note that the tier
     * codes start at 0 for the *compact* tier, so an explicit 0 is the
     * 21-byte hash.
     *
     * The literal is forced: `#[uniffi(default = …)]` takes a literal, not a
     * path, so it cannot name [`DEFAULT_TIER`]. The const assertion below ties
     * the two together at compile time instead.
     */
    public var quality: UInt8

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(w: UInt32, h: UInt32, rgba: Data, gamut: Gamut, 
        /**
         * Quality tier (`0..=4`, ordered by quality). Defaults to the 32-byte
         * default tier, matching [`ChromaHash::encode`] — note that the tier
         * codes start at 0 for the *compact* tier, so an explicit 0 is the
         * 21-byte hash.
         *
         * The literal is forced: `#[uniffi(default = …)]` takes a literal, not a
         * path, so it cannot name [`DEFAULT_TIER`]. The const assertion below ties
         * the two together at compile time instead.
         */quality: UInt8 = UInt8(1)) {
        self.w = w
        self.h = h
        self.rgba = rgba
        self.gamut = gamut
        self.quality = quality
    }

    

    
}

#if compiler(>=6)
extension ImageInput: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeImageInput: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ImageInput {
        return
            try ImageInput(
                w: FfiConverterUInt32.read(from: &buf), 
                h: FfiConverterUInt32.read(from: &buf), 
                rgba: FfiConverterData.read(from: &buf), 
                gamut: FfiConverterTypeGamut.read(from: &buf), 
                quality: FfiConverterUInt8.read(from: &buf)
        )
    }

    public static func write(_ value: ImageInput, into buf: inout [UInt8]) {
        FfiConverterUInt32.write(value.w, into: &buf)
        FfiConverterUInt32.write(value.h, into: &buf)
        FfiConverterData.write(value.rgba, into: &buf)
        FfiConverterTypeGamut.write(value.gamut, into: &buf)
        FfiConverterUInt8.write(value.quality, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeImageInput_lift(_ buf: RustBuffer) throws -> ImageInput {
    return try FfiConverterTypeImageInput.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeImageInput_lower(_ value: ImageInput) -> RustBuffer {
    return FfiConverterTypeImageInput.lower(value)
}


/**
 * An 8-bit-per-channel RGBA color. Each field is in the range `0..=255`.
 */
public struct RgbaColor: Equatable, Hashable {
    public var r: Int32
    public var g: Int32
    public var b: Int32
    public var a: Int32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(r: Int32, g: Int32, b: Int32, a: Int32) {
        self.r = r
        self.g = g
        self.b = b
        self.a = a
    }

    

    
}

#if compiler(>=6)
extension RgbaColor: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRgbaColor: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RgbaColor {
        return
            try RgbaColor(
                r: FfiConverterInt32.read(from: &buf), 
                g: FfiConverterInt32.read(from: &buf), 
                b: FfiConverterInt32.read(from: &buf), 
                a: FfiConverterInt32.read(from: &buf)
        )
    }

    public static func write(_ value: RgbaColor, into buf: inout [UInt8]) {
        FfiConverterInt32.write(value.r, into: &buf)
        FfiConverterInt32.write(value.g, into: &buf)
        FfiConverterInt32.write(value.b, into: &buf)
        FfiConverterInt32.write(value.a, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRgbaColor_lift(_ buf: RustBuffer) throws -> RgbaColor {
    return try FfiConverterTypeRgbaColor.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRgbaColor_lower(_ value: RgbaColor) -> RustBuffer {
    return FfiConverterTypeRgbaColor.lower(value)
}


/**
 * Errors surfaced across the FFI boundary. Maps to a thrown Kotlin/Swift/Python
 * exception.
 *
 * The core encoder panics on invalid input, which is undefined behaviour across
 * an FFI boundary — so every entry point validates first and returns one of
 * these instead. The variants mirror the C ABI's `ChromaHashStatus` codes, so a
 * caller sees the same taxonomy whichever binding it went through.
 */
public enum ChromaHashError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    /**
     * `from_bytes` was given bytes that are not a valid v1 ChromaHash (bad
     * version, tier, reserved bit, or a length that disagrees with the header).
     * `reason` carries the core's precise message.
     */
    case InvalidData(reason: String
    )
    /**
     * A dimension was zero.
     */
    case InvalidDimensions(reason: String
    )
    /**
     * `rgba.len()` was not `w * h * 4`.
     */
    case InvalidLength(reason: String
    )
    /**
     * The quality tier was above [`MAX_TIER`]; codes above it are reserved.
     */
    case InvalidTier(reason: String
    )

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension ChromaHashError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeChromaHashError: FfiConverterRustBuffer {
    typealias SwiftType = ChromaHashError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ChromaHashError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .InvalidData(
            reason: try FfiConverterString.read(from: &buf)
            )
        case 2: return .InvalidDimensions(
            reason: try FfiConverterString.read(from: &buf)
            )
        case 3: return .InvalidLength(
            reason: try FfiConverterString.read(from: &buf)
            )
        case 4: return .InvalidTier(
            reason: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: ChromaHashError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .InvalidData(reason):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(reason, into: &buf)
            
        
        case let .InvalidDimensions(reason):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(reason, into: &buf)
            
        
        case let .InvalidLength(reason):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(reason, into: &buf)
            
        
        case let .InvalidTier(reason):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(reason, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeChromaHashError_lift(_ buf: RustBuffer) throws -> ChromaHashError {
    return try FfiConverterTypeChromaHashError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeChromaHashError_lower(_ value: ChromaHashError) -> RustBuffer {
    return FfiConverterTypeChromaHashError.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Source/target color space. Mirrors [`chromahash::Gamut`].
 */

public enum Gamut: Equatable, Hashable {
    
    case srgb
    case displayP3
    case adobeRgb
    case bt2020
    case proPhotoRgb





}

#if compiler(>=6)
extension Gamut: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeGamut: FfiConverterRustBuffer {
    typealias SwiftType = Gamut

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Gamut {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .srgb
        
        case 2: return .displayP3
        
        case 3: return .adobeRgb
        
        case 4: return .bt2020
        
        case 5: return .proPhotoRgb
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: Gamut, into buf: inout [UInt8]) {
        switch value {
        
        
        case .srgb:
            writeInt(&buf, Int32(1))
        
        
        case .displayP3:
            writeInt(&buf, Int32(2))
        
        
        case .adobeRgb:
            writeInt(&buf, Int32(3))
        
        
        case .bt2020:
            writeInt(&buf, Int32(4))
        
        
        case .proPhotoRgb:
            writeInt(&buf, Int32(5))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGamut_lift(_ buf: RustBuffer) throws -> Gamut {
    return try FfiConverterTypeGamut.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGamut_lower(_ value: Gamut) -> RustBuffer {
    return FfiConverterTypeGamut.lower(value)
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeChromaHash: FfiConverterRustBuffer {
    typealias SwiftType = [ChromaHash]

    public static func write(_ value: [ChromaHash], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeChromaHash.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [ChromaHash] {
        let len: Int32 = try readInt(&buf)
        var seq = [ChromaHash]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeChromaHash.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeImageInput: FfiConverterRustBuffer {
    typealias SwiftType = [ImageInput]

    public static func write(_ value: [ImageInput], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeImageInput.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [ImageInput] {
        let len: Int32 = try readInt(&buf)
        var seq = [ImageInput]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeImageInput.read(from: &buf))
        }
        return seq
    }
}
/**
 * The lowest quality tier: a 21-byte hash. Tier codes are ordered by quality.
 */
public func compactTier() -> UInt8  {
    return try!  FfiConverterUInt8.lift(try! rustCall() {
    uniffi_chromahash_uniffi_fn_func_compact_tier($0
    )
})
}
/**
 * The default quality tier: a 32-byte hash. What [`ChromaHash::encode`] uses.
 */
public func defaultTier() -> UInt8  {
    return try!  FfiConverterUInt8.lift(try! rustCall() {
    uniffi_chromahash_uniffi_fn_func_default_tier($0
    )
})
}
/**
 * The format generation this build writes and accepts.
 */
public func formatVersion() -> UInt8  {
    return try!  FfiConverterUInt8.lift(try! rustCall() {
    uniffi_chromahash_uniffi_fn_func_format_version($0
    )
})
}
/**
 * The highest quality tier this build implements; higher codes are reserved.
 */
public func maxTier() -> UInt8  {
    return try!  FfiConverterUInt8.lift(try! rustCall() {
    uniffi_chromahash_uniffi_fn_func_max_tier($0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_chromahash_uniffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_chromahash_uniffi_checksum_func_compact_tier() != 19023) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chromahash_uniffi_checksum_func_default_tier() != 45813) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chromahash_uniffi_checksum_func_format_version() != 31955) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chromahash_uniffi_checksum_func_max_tier() != 43139) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chromahash_uniffi_checksum_method_batchencoder_encode_batch() != 42834) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chromahash_uniffi_checksum_method_chromahash_as_bytes() != 7674) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chromahash_uniffi_checksum_method_chromahash_average_color() != 8599) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chromahash_uniffi_checksum_method_chromahash_decode() != 1990) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chromahash_uniffi_checksum_method_chromahash_decode_capped() != 61997) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chromahash_uniffi_checksum_method_chromahash_decode_capped_to() != 18999) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chromahash_uniffi_checksum_method_chromahash_decode_to() != 64313) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chromahash_uniffi_checksum_constructor_batchencoder_new() != 49572) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chromahash_uniffi_checksum_constructor_batchencoder_with_threads() != 10330) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chromahash_uniffi_checksum_constructor_chromahash_encode() != 23354) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chromahash_uniffi_checksum_constructor_chromahash_encode_with_quality() != 17637) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chromahash_uniffi_checksum_constructor_chromahash_from_bytes() != 29828) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureChromahashUniffiInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all